server:
  port: 8080

spring:
  application:
    name: zhipu-demo
  main:
    allow-bean-definition-overriding: true
  config:
    import: optional:application-secret.yml
  datasource:
    url: jdbc:mysql://localhost:3306/sc6kd_indv_stl_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  mail:
    host: smtp.qq.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

# 智普AI 配置
zhipu:
  ai:
    api-key: ${ZHIPU_API_KEY}  # 请填写你的智谱AI API Key
    base-url: https://open.bigmodel.cn/api/paas/v4
    model: glm-4
    model-type: zhipu  # 可选: zhipu, deepseek, tongyi
    use-mock: false  # 设置为true使用模拟服务，false使用真实API

# DeepSeek AI 配置
deepseek:
  api-key: ${DEEPSEEK_API_KEY}  # 请填写你的DeepSeek API Key
  base-url: https://api.deepseek.com
  model: deepseek-chat

# 通义千问 AI 配置
tongyi:
  api-key: ${TONGYI_API_KEY}  # 请填写你的通义千问 API Key
  base-url: https://dashscope.aliyuncs.com
  model: qwen-turbo

# 日志配置已移至 logback-spring.xml

# 股票邮件配置
stock:
  mail:
    to: ${STOCK_MAIL_TO}  # 请填写你的QQ邮箱 

# tushare配置
tushare:
  token: ${TUSHARE_TOKEN}  # 请填写你的tushare token
  
# application.yml
management:
  endpoints:
    web:
      exposure:
        include: startup,health  # 暴露startup和health端点
  endpoint:
    startup:
      enabled: true  # 显式启用startup端点（默认已启用，可省略）